require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cargos", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Cargo. As you add validations to Cargo, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:cargo)
  }

  let(:invalid_attributes) {
    attributes_for(:cargo, descricao: nil)
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # CargosController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      Cargo.create! valid_attributes
      get cargos_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cargo = Cargo.create! valid_attributes
      get cargo_url(cargo), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Cargo" do
        expect {
          post cargos_url,
               params: { cargo: valid_attributes }, headers: valid_headers, as: :json
        }.to change(Cargo, :count).by(1)
      end

      it "renders a JSON response with the new cargo" do
        post cargos_url,
             params: { cargo: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Cargo" do
        expect {
          post cargos_url,
               params: { cargo: invalid_attributes }, as: :json
        }.to change(Cargo, :count).by(0)
      end

      it "renders a JSON response with errors for the new cargo" do
        post cargos_url,
             params: { cargo: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          descricao: 'Meu novo Cargo',
          atividades: 'Minhas novas atividades'
        }
      }

      it "updates the requested cargo" do
        cargo = Cargo.create! valid_attributes
        patch cargo_url(cargo),
              params: { cargo: new_attributes }, headers: valid_headers, as: :json
        cargo.reload
        expect([cargo.descricao, cargo.atividades]).to eq([new_attributes[:descricao], new_attributes[:atividades]])
      end

      it "renders a JSON response with the cargo" do
        cargo = Cargo.create! valid_attributes
        patch cargo_url(cargo),
              params: { cargo: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the cargo" do
        cargo = Cargo.create! valid_attributes
        patch cargo_url(cargo),
              params: { cargo: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cargo" do
      cargo = Cargo.create! valid_attributes
      expect {
        delete cargo_url(cargo), headers: valid_headers, as: :json
      }.to change(Cargo, :count).by(-1)
    end
  end
end
